displayName=Glamourer
author=huze
description=Recolor any item
tags=glamour,glamor,colour,recolour,color,recolor,dye,fashion,transmog,blind,accessibility
plugins=io.huze.glamourer.Plugin
build=standard